docs/config-file.txt

I believe there is an incorrect wording in config-file.txt file.
The line 
`array` and `hash` are JSON because almost programming languages and infrastructure tools can generate JSON value easily than unusual format.
should be
`array` and `hash` are JSON because almost all programming languages and infrastructure tools can generate JSON value easily than unusual format.

Fix wording in config-file.txt

---

docs/out_mongo.txt

I think the description would help many users.
I wondered how to change the key name of timestamp, and then I read the source code but I could not find the way, 
and finally get the answer here:
https://github.com/fluent/fluent-plugin-mongo/issues/35

describe about time_key configuration

---

docs/v0.12/quickstart.txt

Added
```
* [Filter Plugins](filter-plugin-overview)
* [Parser Plugins](parser-plugin-overview)
* [Formatter Plugins](formatter-plugin-overview)
```
BTW, where can I write ja docs for v0.12?
There was no `docs/ja/v0.12` directory, or `docs/v0.12/ja` directory.

Add links to v0.12 new plugins from quickstart

---

docs/_buffer_parameters.txt
docs/_timesliced_buffer_parameters.txt
docs/out_webhdfs.txt

* add descriptions about `flush_at_shutdown`
* fix parameters of buffer parameters of webhdfs output, because these are overwritten by that plugin

Fix buffer parameters

---

docs/v0.12/filter_record_transformer.txt

In /articles/filter_record_transformer, `filter_record_modifier` is present, but it should be `filter_record_transformer`?

Fix wrong plugin name in filter_record_transformer's page

---

docs/faq.txt

RHEL 7 ships with quite recent version of Ruby, so the note about -p353 is obsolete. Also, RHSCL should be alternative.
BTW, if you encounter such issue, you might want to consider contact Red Hat suppor, if you are RH subscriber or try to report directly in RH bugzilla, such issue won't be ignored.

Update RHEL 7 FAQ

---

docs/v0.12/in_tail.txt

Just noticed several minutes ago :)

Fix trivial typo in `in_tail` doc

---

docs/common-log-formats.txt
docs/v0.12/common-log-formats.txt

Current sample format can't process [a line including a url with squre bracket](http://fluentular.herokuapp.com/parse?regexp=%5E%28%3F%3Ctime%3E%5B%5E+%5D%2B+%5B%5E+%5D%2B%29+%5C%5B%28%3F%3Clog_level%3E.*%29%5C%5D+%28%3F%3Cpid%3E%5Cd*%29.%28%3F%3Ctid%3E%5B%5E%3A%5D*%29%3A+%28%3F%3Cmessage%3E.*%29%24&input=2016%2F03%2F04+18%3A39%3A05+%5Berror%5D+2264%230%3A+*232080+open%28%29+%22%2Fpath%2Fto%2Fjs%2Fhtml%2Finstream.js+%5B2%5D%22+failed+%282%3A+No+such+file+or+directory%29%2C+client%3A+184.27.179.250%2C+server%3A+example.com%2C+request%3A+%22GET+%2Finstream.js%2520%5B2%5D+HTTP%2F1.1%22%2C+host%3A+%22example.com%22%2C+referrer%3A+%22http%3A%2F%2Fm.dreamers.id%2Flifestyle%2Farticle~3%22&time_format=).
But the square bracket (`[`, `]`) is one of URI characters, according to …

common-log-formats: Fixed the regexp format of nginx/error.log

---

docs/v0.12/in_tail.txt

The enable_watch_timer option was discussed in:
https://groups.google.com/forum/#!topic/fluentd/BBRde4Lyl9E
Setting this parameter to `false` will significantly reduce CPU and I/O consumption when tailing a large number of files on systems with inotify support.
Corresponding PR for code changes:  https://github.com/fluent/fluentd/pull/811

Added enable_watch_timer option

---

config/last_updated.json
docs/common-log-formats.txt
docs/v0.12/common-log-formats.txt

I used the original one for a PHP application and it didn't work so well since the nginx PHP integration would dump multi-line stack traces on each error. The `multiline` format is therefore required for properly parsing the nginx error log.

Improve Nginx Error Log regex with multiline mode

---

views/category.erb

All recipes link is broken.
http://docs.fluentd.org/v0.12/categories/recipes
The `link_to` return relative path.
So all recipe a tag attributes is relative path like this `href="recipe/json/treasure-data"`
and this a tag link to http://docs.fluentd.org/v0.12/categories/recipe/json/treasure-data
But this link should be path from root . ( http://docs.fluentd.org/recipe/json/treasure-data ).
So I add / in the top.

fix recipe path

---

docs/v0.10/_formatter_common_parameters.txt
docs/v0.14/_formatter_common_parameters.txt

I fixed a typo of `time_key` explanation.
'xOptional' -> 'Optional'

fix_typo of time_key

---

scripts/conf/input/nginx.conf

The example for nginx.conf references the Apache access log instead of the Nginx access log.

Fix nginx.conf

---

docs/v0.12/nodejs.txt

Changed npm package link to official package. Current link is invalid and other similar packages are outdated.

Update npm package link

---

docs/v0.12/install-by-docker.txt

Fix typo ~~`/tmp/fluentd/conf`~~ `/tmp/fluentd.conf`

Fix typo /tmp/fluentd/conf -> /tmp/fluentd.conf

---

lib/toc.en.v0.12.rb

I found that we have 2 out_splunk links in v0.12 documentation.

Drop duplicated occurrence of out_splunk in v0.12 documentation

---

lib/toc.en.v0.14.rb

I forgot to update toc when I added out_webhdfs article ( https://github.com/fluent/fluentd-docs/pull/291 ) . So I updated it.

v0.14: Update toc for out_webhdfs

---

docs/v0.14/plugin-update-from-v12.txt

This will prevent upgrading Fluentd to v2 automatically.
This will avoid some weird problems about upgrading fluent-plugins.

Add recommended dependency in plugin's gemspec

---

docs/v0.14/api-plugin-output.txt

Otherwise, embedded ruby code is shown like below:
:::ruby class MyAwesomeOutput < Output config_section :buffer do config_set_default :chunk_keys, [‘tag’] config_set_default :chunk_limit_size, 2 * 1024 * 1024 # 2MB end end
This lines should be shown as:

Fix shortage of indentation for syntax highlights

---

docs/v0.10/forwarding-over-ssl.txt
docs/v0.12/forwarding-over-ssl.txt

e.g. https://docs.fluentd.org/v0.12/articles/forwarding-over-ssl#setup:-sender

fix snippet formatting in forwarding-over-ssl

---

lib/toc.en.v0.14.rb

* in_secure_forward
* in_forward supports TLS connection
* in_scribe
* unmaintained
* in_multiprocess
* multi process is built-in functionality

Remove outdated input plugins from table of contents for v0.14

---

docs/v0.14/install-by-gem.txt
docs/v0.14/install-from-source.txt

We can add explanation of `$ fluentd -c ./fluent/fluent.conf -vv &`. When I run this command, I confused because this logs show me what? Is this building now? So, we promote users to next step.
Finally, We can't stop fluentd process by `Ctrl + C` . Let's write how to exit.
For example `$ pkill -f fluentd`

We can improve Run example.

---

docs/v0.14/buffer-plugin-overview.txt
docs/v0.14/buffer-section.txt
docs/v0.14/filter-plugin-overview.txt
docs/v0.14/input-plugin-overview.txt
docs/v0.14/output-plugin-overview.txt
docs/v0.14/parser-plugin-overview.txt
docs/v0.14/performance-tuning.txt

A bit more precisely:
* Fix number of plugin types
* Fix badly displayed 'workers' example
* Fix bad parameter name

Fix some minor typos

---

docs/v0.14/td-agent-v2-vs-v3.txt

Currently, td-agent v2 had been released for Debian Stretch.
But td-agent v3 is not released yet for it.

Add Debian Stretch entry to supported platforms table

---

docs/v1.0/life-of-a-fluentd-event.txt

The document which explains how fluentd processes various events
has a fairly confusing title ("Configulation File").
> https://docs.fluentd.org/v1.0/articles/life-of-a-fluentd-event
This patch fixes its title to be more descriptive.

docs: Use a less confusing page title.

---

docs/v0.10/config-file.txt
docs/v0.12/config-file.txt
docs/v1.0/config-file.txt

Most browsers nowadays will not load embedded HTTP iframes in HTTPS pages anymore. 
For example, recent versions of Firefox will produce this warning message while loading https://docs.fluentd.org/v0.12/articles/config-file:
> Blocked loading mixed active content “http://www.slideshare.net/slideshow/embed_code/34610229”
This commit fixes those unsecured iframe links to avoid loading problems on the production environment.

docs: Use HTTPS links for slideshare to avoid mixed-content warnings.

---

docs/v1.0/out_mongo.txt
lib/toc.en.v1.0.rb

v0.14/v1.0 ready out_mongo plugin is version 1.0.0.
Users should use fluent-plugin-mongo v1.0.0 when they use td-agent3/Fluentd v0.14 or v1.0.
So, I use `1.0.0` in introduced version.

Add out_mongo document for v1.0

---

docs/v1.0/life-of-a-fluentd-event.txt

This patch fixes grammatical errors (incorrect verb forms) in the "Life  of a Fluentd event" document.

docs: use correct third-person singular verbs.

---

docs/v1.0/life-of-a-fluentd-event.txt

* Use possessive form to make it serve as a determiner (it -> its)
* Remove a stray article ("is *an* important for reliability")

docs: fix miscellaneous grammatical errors.

---

docs/v1.0/life-of-a-fluentd-event.txt

This patch removes 's' from 'files' to make the subject match the verb.

docs: fix singular/plural forms

---

docs/v1.0/php.txt

This patch makes the PHP logging manual up-to-date.
Notably, the current manual relies on 'src/Fluent/Autoloader.php'
which has been deprecated for almost 2 years now:
> https://github.com/fluent/fluent-logger-php/commit/ad738740b
So I removed the obsolate examples and replaced them with the
latest, composer-based instructions.
**Note**
Those new instructions are mostly imported from the README file
of the upstream project (fluent/fluent-logger-php). For details, see:
https://github.com/fluent/fluent-logger-php#installation

docs: update the documentation for fluent-logger-php

---

docs/v1.0/java.txt
docs/v1.0/nodejs.txt
docs/v1.0/perl.txt
docs/v1.0/php.txt
docs/v1.0/python.txt
docs/v1.0/ruby.txt
docs/v1.0/scala.txt

The current manual instructs users to use the following command
for restarting a process:
> $ sudo systemctl start td-agent.service
But `systemctl start` will do nothing if the target process is
already runnning. Instead, we should use the `restart` command.

docs: use 'systemctl restart' to restart a process

---

docs/v1.0/filter_geoip.txt
lib/toc.en.v1.0.rb

fluent-plugin-geoip v1.0.0 is released recently.
So it's time to add document for filter_geoip instead of out_geoip.

Add document for fluent-plugin-geoip

---

views/layout.erb

Without z-index styling, the popup can be overlaid by the normal elements in the page.
This leads to an odd UI elements arrangement.
For example, look at the screenshot below:
This patch sets z-index of the popup, so that it gets always stacked on the other elements.
After this commit, the popup will look like:

views: Adjust the z-index of the `got-question` popup.

---

docs/v1.0/scala.txt

This commit fixes links in the logging manual for Scala.
Several issues are fixed. Specifically:
1. The upstrem project was transferred to `fluent` organization two years ago.
2. The "ChangeLog" file was renamed to "RELEASE_NOTES.md".
3. Since 2016, the *master* branch of the upstream project has not been maintained
and we need to use the *develop* branch instead.
For details about the branch migration (from master to develop), please see the following issue:
https://github.com/fluent/fluent-logger-scala/issues/32

docs: Fix links to the fluent-scala-logger project.

---

docs/v1.0/free-alternative-to-splunk-by-fluentd.txt

This is a small patch that adds a code example to restart rsyslogd
using `systemctl(1)`.
Since the other parts of this document contains instructions for
systemd users, it's natural to expect this part also contains one.
Here is how it looks like after this patch:

Add a missing instruction for systemd users.

---

app/css/base.css

For now, the 'color' directive in the `.btn-look` selector has no effect on the actual appearance of the buttons, because it gets overridden by the common color settings of `<a>` tag. This leads to somewhat odd-looking buttons.
This patch fixes the styling definition to make these buttons look more readable.
Here is how it looks like now:
...and after this patch:

app: Make "What is fluentd?" button look nice

---

docs/v0.10/enterprise-support-portal.txt
docs/v0.10/support.txt
docs/v0.12/free-alternative-to-splunk-by-fluentd.txt
docs/v0.12/kubernetes-fluentd.txt
docs/v1.0/enterprise-support-portal.txt
docs/v1.0/free-alternative-to-splunk-by-fluentd.txt
docs/v1.0/support.txt

The official website 'fluentd.treasuredata.com' has been moved to
'www.treasuredata.com/fluentd/'. This migration made several links
in the manual pages broken.
For instance, we need to fix a link to Splunk article as follows:
* old: https://fluentd.treasuredata.com/splunk-optimize/
* new: https://www.treasuredata.com/fluentd/splunk-optimize/
This patch updates all these links to 'fluentd.treasuredata.com'.

docs: Fix the outdated links to 'fluentd.treasuredata.com'

---

docs/v0.10/free-alternative-to-splunk-by-fluentd.txt
docs/v0.12/free-alternative-to-splunk-by-fluentd.txt
docs/v1.0/free-alternative-to-splunk-by-fluentd.txt

This patch fixes a subtle typo in the manual.
This commit also includes  fixes for the old revisions of this document
(namely v0.10 and v0.12)

docs: Fix a typo (Dowload -> Download)

---

views/layout.erb

This patch fixes the bug reported by #258.
Currently, we use "opacity" attribute to hide the newsletter popups in the left-top corner.
For example, we specify `opacity: 0;` to make these popups invisible.
This leads to, however, somewhat confusing UI, because these popups remain clickable
even if they are in the "hidden" state:
Instead, we should use `display: none;` to make these popups invisible.
This setting should make these popups unclickable (if they are in the "hidden" state),
hence will prevent users from clicking them accidentally.

views: Use `display: none;` to make hidden popups unclickable.

---

docs/v0.12/splunk-like-grep-and-alert-email.txt
docs/v1.0/splunk-like-grep-and-alert-email.txt

For now, the "browsing recipes" link does not work properly, and it
leads users to a non-existent page (in any version of the document).
The reason behind this issue is a bit entangled:
- In v1.0 docs, the "recipes" page is disabled, and thus, does not exist.
- In v0.12 docs, the page *does* exist. But the URL is wrongly pointing to '/v1.0/categories/recipes'.
So I fixed the link as follows:
- For v1.0, just delete the link.
- For v0.12, fix the url to point to '/v0.12/categories/recipes'

doc: Fix a broken link to '/categories/recipes'

---

docs/v0.12/trouble-shooting.txt

As reported by #380, the current documentation on enabling the debug flag
is largely obsolete, as the `init.d` script has been reorganized in td-agent v2.2.1.
This patch update the manual to use the new variable `TD_AGENT_OPTIONS`.
(with a side note for users who use the older td-agent <2.2.1).
I confirmed the new instruction works on both Ubuntu 16.04 and CentOS 7.4
with the latest td-agent2 (v2.3.6).

 docs: Use TD_AGENT_OPTIONS to turn on a debug flag. 

---

docs/v1.0/buffer-section.txt

This patch adresses the issue reported by #280.
For now, the documentation says that `flush_at_shutdown` gets
turned on by default for file buffers.
However, as far as I can tell, this is just plain wrong. In fact, for a
persistent buffer like buf_file, the parameter is turned *off* by default
(we can confirm this in plugin/output.rb).
This patch fixes the issue by updating the buffer section manual.

docs: Fix the default value of the `flush_at_shutdown` parameter.

---

lib/toc.en.v1.0.rb

'Updating plugins from v0.12 to v0.14' ->
'Updating plugins from v0.12 to v1.0'
Because the title of plugin-update-from-v12.txt has been already
updated for v1.0.

Update link text for v1.0

---

docs/v1.0/splunk-like-grep-and-alert-email.txt

This is besically a preparation patch for the upcoming fixes of this
apache/email integration article. This patch should make the text much
easier to read (hence, easier to audit).
This patch only includes minor cosmetic changes, and does not modify
the actual content of the text.

docs: Fix markmown formatting of the "Email Alerts like Splunk"

---

docs/v1.0/splunk-like-grep-and-alert-email.txt

This patch updates the "Email Alerts like Splunk" article to use the
`td-agent` wrapper, as this is the preferred way to manage the fluentd
daemon these days.
The old instructions for standalone `fluentd` are also preserved, so
that we do not confuse users who still rely on them.

docs: Update Apache/Email configuration examples to use `td-agent`

---

docs/v1.0/splunk-like-grep-and-alert-email.txt

This patch is a collection of tiny fixes to make this how-to article
more readable. It includes two categories of improvements:
- GENERAL TONE: Make the general tone of this article more consistent
with other articles. A few assertive statements are dropped (like,
'The competing product X is "quite expensive"').
- CODE EXAMPLE: Trim down the configuration example to make it more
concise. The inline annotations in the example are reformatted for
readability.
This patch should make the article more approachable for users.

docs: Clean up the "Email Alerts like Splunk" article

---

docs/v0.12/_buffer_parameters.txt
docs/v0.12/_timesliced_buffer_parameters.txt
docs/v0.12/out_webhdfs.txt
docs/v1.0/out_webhdfs.txt

For now, the documentation is a bit ambiguous as to where the (seemingly
arbitrary) "131072 sec" limit comes from. Apparently, this is a source of
confusion for plugin users.
This patch fixes this issue by explaining the context behind it in more detail.
This patch solves the problem reported by #214

docs: Fix an ambiguous sentence in the description of `max_retry_wait`.

---

docs/v0.12/splunk-like-grep-and-alert-email.txt

This patch is the backport of the following patches to v0.12:
- 725ae32: Clean up the "Email Alerts like Splunk" article
- 31be084: Update Apache/Email configuration examples to use `td-agent`
I confirmed it actually works on Ubuntu Xenial using td-agent v2.3.6.

docs: Backport the changeset into v0.12 ("Email Alerts like Splunk")

---

docs/v0.12/splunk-like-grep-and-alert-email.txt
docs/v1.0/splunk-like-grep-and-alert-email.txt

- User proper spelling: alart -> alert
- Add cautionary note for file permission issues.

docs: Fix small nits in the article "Email Alerts like Splunk"

---

docs/v1.0/api-plugin-helper-thread.txt

For now, the example code does not work (results in a runtime error)
since it tries to load non-existent plugin 'plugin:threads'.
We can get it to work fine just by fixing it to use 'plugin:thread'.

doc: Fix an erroneous example code in "Thread Plugin Helper API"

---

docs/v1.0/life-of-a-fluentd-event.txt

The `excludeN` option (of filter_grep) was deprecated in Fluentd v0.12
in favour of the `<exclude>` syntax.
This patch migrates the example codes in the "Life of a Fluentd Event" article.
I confirmed these codes actually work using td-agent v3.1.

docs: Use `<exclude>` blocks instead of `excludeN` options

---

docs/v0.12/filter-modify-apache.txt
docs/v1.0/filter-modify-apache.txt
lib/toc.en.v0.12.rb
lib/toc.en.v1.0.rb

This patch savages the old article on how we can use filters to
transform event streams. In order to get it work with Fluentd v1.0,
the texts (including the code examples) are thoroughly rewritten.
Although most of the content is already covered by the plugin manuals,
I think a good number of users will still find this article helpful.
Note: For the context behind this pull request, see #413.

docs: Migrate "filter-modify-apache.txt" to v1.0    

---

lib/toc.en.v0.12.rb
lib/toc.en.v1.0.rb

This small patch is my attempt to improve the categorization to give
the better perspective to newer readers:
1. Use more descriptable titles to categories
2. Reclassify articles to group related ones together
For the context of this patch, please see the issue #413.

lib: Clean up the categorization of articles in "Use Cases".

---

docs/v1.0/install-by-deb.txt
docs/v1.0/install-by-gem.txt
docs/v1.0/install-by-msi.txt
docs/v1.0/install-by-rpm.txt
docs/v1.0/quickstart.txt

For now, we mix several notations to denote instruction steps, even
in the same article. For example, in the "Install-by-deb" article,
we see something like below:
[Table of Contents]
Step 0: Before Installation
Step 1 : Install from Apt Repository
Step2: Launch Daemon
See? This seems kinda ugly, and we certainly would better be more consistent.

docs: Be consistent in numbering instruction steps.

---

docs/v0.12/buffer-plugin-overview.txt

This is a collection of small fixes to the buffer-overview article.
It includes three categories of improvements:
1. Enlarge the image to make the diagram easier to view.
2. Avoid abusing bullet points for denoting sections.
3. Add a missing language identifier to a code block.
This commit is basically a preparation for the subsequent set of patches.

docs: Fix formatting of the article "Buffer Plugin Overview"

---

docs/v0.12/buffer-plugin-overview.txt

This section has grown to the point that it requires non-trivial
mental efforts just to follow the explanation. We can make reader's
life easier by using bullet lists for better presentation, splitting
the content into sub-sections, and adding senslble titles to them.
This patch introduces these improvements described above.

docs: Improve the overall structure of the "Buffer Structure" section.

---

docs/v0.12/buffer-plugin-overview.txt

This patch addresses various issues in the article ["Buffer Plugins Overview"](https://docs.fluentd.org/v0.12/articles/buffer-plugin-overview).
This patch should improve the overall readability in a few key aspects:
* Remove the obsolate diagram and replace it with correct one.
* Provide comprehensive explanations of buffer-related configuration options.
This should be very helpful to new users.
* Restructure the overall content to make it significantly easier to
follow.
Note that this patch is for the v0.12 article. For v1.0 article, we need
another series of patches.
This patch is the fix for the issues reported by #255.

docs: A major rewrite of the "Buffer Plugin Overview" article.

---

docs/v1.0/performance-tuning-single-process.txt

This patch removes an obsolete link to the article on "Performance
Tuning (Multi-Process)".
Note that the content of this article has been largely deprecated
since the arrival of the new (built-in) multi-processing feature,
and, in fact, this article has never been ported to v1.0.
This patch is the quick fix for the issue #428.

docs: Remove dead link to the old multi-process tuning documentation.

---

docs/v1.0/buffer-plugin-overview.txt

The current documentation lacks the explanation on how Fluentd
calculates the wait interval for each retry attempt. Apparently,
this seems to be a source of confuse for some users.
This patch attempts to fill the gap, by adding a small section
deidcated to this topic.
This patch is a part of #427.

docs: Add a section to explain how exponential backoff works.

---

docs/v1.0/in_tail.txt

A user suggested that the default value of `enable_watch_timer`
might be misdescrived. As it turns out, it was wrong indeed.
See the line 80 of lib/fluent/plugin/in_tail.rb at Fluentd v1.10:
config_param :enable_watch_timer, :bool, default: true
desc 'Enable the stat watcher based on inotify.'
This patch fixes the issue reported by #435.

docs: Fix the default value of `enable_watch_timer` to true

---

docs/v1.0/buffer-plugin-overview.txt

In the current implementation, *all* the data in the output queue will
be discarded if it fails to write out a chunk within the given retry limit.
Since this event necessarily entails a (possibly huge) data loss, we
definitely need to document the behaviour in a clear way.
This patch adds the documentation to the buffer-plugin-overview page.
This patch is a part of #427.

docs: Document what occurs if the retry count exceeds the limit.

---

docs/v1.0/buffer-plugin-overview.txt

This patch adds an illustrative example to describe how to control
the retry behaviour in practice. This example should be helpful especially
for new users.
This patch is a part of #427

docs: Add a configuration example to control retry behaviours.

---

docs/v1.0/in_forward.txt

I've noticed that the documentation around the TLS/SSL encryption
feature is rather thin for now. Since a non-negligible number of users
(apparently) have an interst in this feature, we'd probably better to
document it well.
This patch adds a brief tutorial for setting up a TLS/SSL enabled
(in-)forwarding server.
This pull request is a part of a series of patches for #431.
https://www.fluentd.org/blog/fluentd-v0.14.12-has-been-released

docs: Add a brief tutorial for setting up TLS/SSL encryption.

---

docs/v1.0/buffer-plugin-overview.txt

This patch adds an elementary introduction on the mechanism of
a buffer plugin, which should be much friendlier to novice users.
For now, the introduction covers the following topics:
1. What is a chunk?
2. How a chunk is managed by the plugin?
3. What is "stage" (or "queue")?
...and will be extended further in the subsequent patches.
This patch is a part of the issue #427.

docs: Add a simpler explanation on how buffers work.

---

views/layout.erb

For now, accessing to "https://fluentd.org" results in a connection timeout.
This patch is a quick fix to update the URL to "https://www.fluentd.org".
This patch fixes the issue #443 and #442.

views: Fix a broken link to fluentd.org

---

app/css/header.css

I've noticed that the header area of the documentation site:
- has a truncated logo image. This is the consequence of having a
display frame (169x70) that is smaller than the image itself (170x70).
- is aligned a bit poorly, due to lacking margin settings.
This patch tries to fix these issues by adjusting the style sheet.
*Before*
*After*

app: Adjust the CSS settings of the common header.

---

docs/v0.12/monitoring-prometheus.txt

Only initial installation step uses `td-agent`.
But, other commands use `fluent`

docs: Fix a installation command

---

docs/v0.12/monitoring-prometheus.txt

While merging #430, I found several typos exist in this article.
So I've applied a spell checker to this article and squeezed out
all of the misspellings found.

docs: Fix typos in the "Monitoring by Prometheus" article.

---

docs/v0.12/monitoring-prometheus.txt

This trivial patch makes the article compatible with td-agent.
Presumably, there are many users who does not even realise `fluentd`
executable has been installed in their system (this is not so uncommon
since, in the first place, td-agent is supposed to abstract it away).
This patch should be helpful to these users.

docs: Fix the Prometheus article to support td-agent systems.

---

docs/v1.0/in_forward.txt
docs/v1.0/out_forward.txt

In e0253bf, I've updated the `in_forward` manual to include the user
instructions for setting up TLS/SSL encryption.
This is the counter-part patch, which adds an explanation on how to
connect to an encryption-enabled server.
With this patch applied, the task of setting up an end-to-end
encrypted forwarding topology should become (relatively) easier.
This patch fixes the issue reported by #431.

docs: Explain how to set up TLS/SSL encryption in out_forward.

---

docs/v1.0/out_elasticsearch.txt

The following sentence does not make sense if considered as a description
for "user, password, path, scheme. ssl_verify":
> If you specify this option, host and port options are ignored.
This seems to me like a plain misplacement as suggested by #452.

docs: Move a misplaced sentence to the correct place.

---

docs/v1.0/out_forward.txt

This patch adds an instruction to enable the gzip compressed forwarding
introduced in Fluentd v0.14.7.
This feature should be very useful especially for cloud environments
(like AWS) where billing occures based on the transferred data volume.
This patch address the issue #431.

docs: Add a user guide to enable data compression in out_forward.

---

docs/v0.12/filter_record_transformer.txt
docs/v1.0/filter_record_transformer.txt

What the documentation basically states about these directives is:
tag_prefix[N] = tag[0:N]
tag_suffix[N] = tag[len(tag)-N:]
But apparently this is not how it works. The correct description of
these directives is:
tag_prefix[N] = tag[0:N]
tag_suffix[N] = tag[N:]
This patch fix the erroneous documentation and add some examples to
ease the understanding of readers.

docs: Fix the confusing documentation for tag_prefix and tag_suffix.

---

docs/v1.0/in_http.txt

I noticed that some newer features of in_http (mostly introduced in
v0.14) have not properly documented yet. In particular:
1. We can post records in MessagePack format
2. We can leverage 'Content-Type' header to post raw JSON data.
This patch adds a brief explanation for each feature, accompanied with
a command-line example.

in_http: Add explanations for undocumented fetures.

---

docs/v1.0/in_http.txt

I belive these two features deserve better publicity, since they have
obvious real-world applications. So I applied the following modification:
- Move the description for `time` parameter to "Basic Usage"
- Add a more descriptive title to the section for `<parser>`
Also a handful of small improvements are included in this patch. These
should allow users to skim through the contents with more ease.

in_http: Improve the documentation for `time` parameter and `<parser>`

---

docs/v1.0/in_http.txt

This patch is a collection of minor fixes to cut the "rough edges"
I noticed while reading the article. Most are editorial fixes.
- Prefer more consistent word choices (http -> HTTP)
- Use the consistent port number (8888 vs 9880)
- Add more working code examples (Sending data in msgpack format)
- Brush up plugin descriptions.

in_http: Apply small fixes to the content texts.

---

docs/v1.0/update-from-v0.12.txt

Sometimes td-agent 2 rpm/deb users doesn't know how to upgrade td-agent
2 to td-agent 3. This change will help that they upgrade td-agent.

Add document for upgrading td-agent 2 to 3

---

docs/v0.12/logging.txt
docs/v1.0/logging.txt

- Fix the end tag for filters. Use `</filter>` instead of `</match>`.

Update logging docs: Fix the end tag for filters in logging for v0.12 and v1.0

---

docs/v1.0/monitoring-prometheus.txt

This patch updates the manual to use the newer versions (v1.0.0 or later)
of fluent-plugin-prometheus.
In the process of creating this patch, I've actually confirmed that the
instructions of the article can be followed without any problem using
fluent-plugin-prometheus v1.0.1. So the article does not need to be updated
beyond this trivial fix.

docs: Update the version of prometheus to v1

---

docs/v0.12/monitoring-rest-api.txt
docs/v1.0/format-section.txt
docs/v1.0/free-alternative-to-splunk-by-fluentd.txt
docs/v1.0/monitoring-rest-api.txt

This patch is a collection of fixes of typos I found in the manual.

docs: Fix various typos in articles

---

docs/v1.0/install-by-msi.txt

Because td-agent3 for Windows has been released with Ruby 2.4.
ref: https://github.com/treasure-data/omnibus-td-agent/pull/154

Remove Ruby version note on WIndows

---

docs/v1.0/api-config-types.txt
docs/v1.0/filter_grep.txt
docs/v1.0/parser_ltsv.txt
docs/v1.0/parser_regexp.txt

I assume that Fluentd next version is 1.2.0.
Please merge this PR after release new version of Fluentd that
includes regexp type support and filter_grep's "and/or" directive.

Update about regexp type and/or directive

---

docs/v0.12/routing-examples.txt
docs/v1.0/routing-examples.txt

The [Routing Examples](https://docs.fluentd.org/v1.0/articles/routing-examples#re-route-event-to-other-label) page refers to the `out_relabel` plugin using a link to [articles/relabel](https://docs.fluentd.org/v1.0/articles/relabel), which should be [articles/out_relabel](https://docs.fluentd.org/v1.0/articles/out_relabel).
Both v1.0 and v0.12 have this issue. This pull request fixes them both.

Fix bad links for out_relabel plugin

---

docs/v1.0/buffer-plugin-overview.txt

This patch fixes subtle errors in the article "Buffer Plugin Overview";
- Follow the capitalization rule for each title consistently
- Fix a typo: `Normaly` -> `Normally`
- Emphasize the important warning
No actual content has been updated.

Fix minor grammatical issues (typo and mismatched capitalization etc.)

---

docs/v1.0/buffer-plugin-overview.txt

@repeatedly I added the documentation of the new feature introduced in
Fluentd v1.2.0. Please feel free to correct it if something is stated wrongly.
This patch adds the explanation for the graceful recovery system
implemented in Fluentd v1.2.0.
Most of the content are derived from the release note (v1.2.0).
For details see below:
https://www.fluentd.org/blog/fluentd-v1.2.0-has-been-released

Add documentation for the new recovery feature for broken chunks

---

docs/v1.0/in_forward.txt

The commit 8c33943 fixes `<transport tls>` to `<transport>` in an
assumption that the `tls` part is mistyped.
However, it is NOT a typo. In fact, if we define a transport section
without the argument, Fluentd won't enable TLS encryption. So we
need to revert the changeset done by #479.
See `lib/fluent/plugin_helper/server.rb:72` for details:
https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin_helper/server.rb#L71

Revert "Update in_forward.txt"

---

docs/v1.0/in_forward.txt

This patch provides users a step-by-step instruction to enable mutual
authentication for the `in_forward` plugin.
The list of the improvements is:
- Add an example configuration to the section.
- Explain how to check the auth mechanism is working correctly
- (minor fix) Apply capitalizatin rule consistently for titles
- (minor fix) Say just "TLS", not "TLS/SSL"

Add detailed instruction to set up TLS mutual authentication

---

docs/v1.0/in_forward.txt
docs/v1.0/out_forward.txt

This patch adds a step-by-step instruction to enable the challenge-response
authentication mechanism, which was introduced in Fluentd v0.14.5.
For details, see: https://github.com/fluent/fluentd/pull/1136
Since `out_forward` has not supported TLS mutual authentication yet, this is
the only built-in mechanism to prevent rogue clients from connecting.
So this guide should be still somewhat useful.

Add a guide to set up password authentication for in/out_forward

---

docs/v1.0/post-installation-guide.txt

This patch includes a number of improvements suggested by https://github.com/fluent/fluentd-docs/pull/500.
- Update the example to use `in_kafka` instead of `in_elasticsearch`
- Use the absolute path `/usr/sbin/td-agent-gem` to invoke the plugin manager

Apply miscellaneous feedbacks to "Post Installation Guide"

---

docs/v1.0/plugin-update-from-v0.12.txt

This patch fixes the typos I found while reading the article.
It also contains a minor fix on the form of verbs (it is singular
vs plural thingy).

Fix various typos in the article "Plugin Update From v0.12"

---

docs/v1.0/out_forward.txt

This patch adds a missing docuemtation for an out_forward parameter
which was introduced in Fluentd v0.14.12.
See https://github.com/fluent/fluentd/commit/9cfcf925 for details of the option.
I also fixed a minor typo in the page (serveral -> several)

out_forward: Add the documentation for 'ignore_network_errors_at_startup

---

docs/v0.12/config-file.txt
docs/v1.0/config-file.txt

Jesse McAllister pointed out that we should describe how match patterns
work in more general way, because these rules are applied not only to
`<match>` tags but also to `<filter>` tags.
See the ticket #490 for details
This patch updates the manual pages based on his suggestion.

config-file: Create a new section to explain how match patterns work

---

docs/v1.0/out_stdout.txt

This patch is based on the suggestion by Eugen Cristea.
See the ticket #505 for details.

out_stdout: Remove an irrelevant note from the documentation.

---

docs/v1.0/in_forward.txt

Signed-off-by: Maxime Carrière <mcarriere@seedbox.com>

Fix a typo in the in_forward documentation

---

docs/v1.0/out_elasticsearch.txt

MartinVUALTO points out that configuration parameters are poorly
documented in the manual of `out_elasticsearch` right now.
I basically agree with this observation. So I rewrote the most of
the descriptions in the manual and added more examples for them.
Also I fixed a number of typos found in the article.
@cosmo0920 Can you check this update and report back to me if there is
something described wrongly?

elasitcsearch: Update the documentation for plugin parameters.

---

docs/v1.0/in_forward.txt

It's `shared_key`, not `secret_key`.

In_forward: Fix typo in example

---

docs/v1.0/in_http.txt

This parameter was addeded in 2014, but not documented yet.
See https://github.com/fluent/fluentd/issues/86 for the background and rationale of this feature.

in_http: Add the missing description for `respond_with_empty_img`

---

docs/v1.0/in_monitor_agent.txt

This patch documents the monitor agent option which has not been
described in the manual page properly.
Note that, as opposed to the name, this option is intended to allow
users to _exclude_ the 'retry' bit from the response, so we would be
better to explain our intention clearly here.

in_monitor_agent: Add a missing documentation for `include_reply`

---

docs/v1.0/in_monitor_agent.txt

This plugin supports a number of query parameters which allows users
to modify the output format dynamically. I think this feature is
somewhat useful to interested users (especially for debugging).
This patch adds the documentation that explains 1) what parameters
are available and 2) how to use them.

in_monitor_agent: Add a new section 'Use query params to tune outputs'

---

docs/v1.0/in_monitor_agent.txt

in_monitor_agent has an undocumented feature that allows users to
retrieve metrics in LTSV format (instead of JSON).
Since this feature seems to be useful, let's describe this feature
on the manual page.

in_monitor_agent: Add a note on how to retrieve data in LTSV format.

---

docs/v1.0/in_exec.txt

This patch expands the section "Use Cases" to include a much simpler
example that shows how to utilize the `in_exec` plugin.
Two notable points:
1) One can use pipe notations '|' in the `command` option.
2) `<parse>` option can used to handle unstructured data (e.g.
space-separated values on /proc/loadavg)

in_exec: Add a simple example to fetch load average stats

---

docs/v1.0/rpc.txt

This RPC endpoint was added in 8507b3c (roughly two years ago) but not
documented yet. So add the documentation for it.
Also this patch applies a small clean-up on the "RPCs" section, which
should make the manual a little easier to read.

rpc: Add documentation for '/api/processes.flushBuffersAndKillWorkers'

---

docs/v1.0/in_monitor_agent.txt

This improves the explanation of the plugin configuration:
- Explain clearly 1) that it is recommended to set the `@id` option on
each plugin and 2) what happens if you don't do it
- Fix a small error in the example (`@id in_forward` is appropriate
in this context, not `@id out_forward`)
- Use a better section title.

in_monitor_agent: Update the example configuration

---

docs/v1.0/rpc.txt

Basically the RPC feature is a thin wrapper over signal handlers
(indeed, these RPC endpoints send corresponding signals on each
request) and it is meant to provide users to more approachable way
to kick those triggers.
This patch polishes up the explanation based on this observation.
TODO: We should explain some endpoints are not usable on Windows.

rpc: Clean up the documentation

---

docs/v1.0/buffer-section.txt

This salvages bits from a v0.14-era release note, which is still
applicable to the latest version of Fluentd.
https://www.fluentd.org/blog/fluentd-v0.14.7-has-been-released
For the details of this patch, see the ticket #526.

buffer-section: Add small notes on how compression works in Fluentd

---

docs/v1.0/out_forward.txt

This feature is indeed a quite old beast. It had been introduced in
v0.10.4 (released in 2011) and is being enabled by default in 2018.
Still, there are no proper documentation on how this feature works
and (especially) what the threshold variable `φ` means.
This patch is my attempt to add a general explanation for this failure
detection feature.

Add an explanation for the "Phi accrual failure detector".

---

docs/v1.0/in_tail.txt

Caused me to write the following:
```
path ["/var/log/apache2/*.access.log", "/var/log/apache2/access.log"]
```
Might be worth making it a bit more explicit perhaps?

in_tail: State the difference in exclude_path and path formats

---

docs/v0.12/parser-plugin-overview.txt
docs/v1.0/parser-plugin-overview.txt

kriston13 points out that the configuration example in the current
manual page is not very well chosen because it fails to describe how
one can modify the parser behaviour through its options.
This patch fixes the manual to use a more concrete example (in_tail
\+ parser_nginx).

parser: Use a more concrete example to illustrate basic usage

---

docs/v1.0/filter_stdout.txt

We just need to be clear that this document has already upgraded to
v1.X, so that we do not confuse readers.
I also removed the note on timestamps since what it claims does not
seem to be true anymore.

Migrate the manual on filter_stdout to version 1.X

---

docs/v1.0/api-plugin-output.txt

This should give readers a more concise overview on how each buffering
mode work and what is the characteristics of each.
Also this improves the overall structure a bit, by moving the part on
"format mode" into a separate section.
Read #541 for the underlying motivation of this patch.

output: Clean up the explanations of various buffering modes

---

docs/v1.0/api-plugin-output.txt

The whole point of the #format interface is to allow plugins to avoid
overheads of encoding/decoding chunks, and developers generally do not
need to care about it if there is no obvious cost-saving opportunity.
So let's explain it clearly, not leaving developers figuring out by
themselves.
See #541 for the context of this patch

output: Clean up the explanation around the #format interface

---

docs/v1.0/out_elasticsearch.txt

In particular, it urges users to confirm that their Elasticsearch
server is actually compatible with the client library installed on
their host machine.
For the background information of this patch, please read #537.

elasticsearch: Add a cautionary note on client version compatibility

---

docs/v1.0/api-plugin-output.txt

This is the first cut at improving the orverall structure of this article.
For the background information of this patch, see #541
In particular, this allows readers to skim through all the available
methods provided by the `Fluent::Plugin::Output` class. This also
makes it possible to navigate to the target document through in-page
links.
So I think this will be a good improvement for many developers.

output: Reorganize the article "Writing Output Plugins"

---

docs/v1.0/api-plugin-output.txt

This patch adds a new section "How Buffers Work", which is a collection
of various existing explanations on buffers.
The new section should serve as an introductory course on buffers for
new-comers. (Note: I left more advanced topics to the other section
"Development Guide")

output: Group buffer-related sections into "How Buffers Work"

---

docs/v1.0/api-plugin-output.txt

This is a minor patch to make the section titles in the article more
descriptive.
For example, the section title "Methods" gets modified to "List of
Interface methods", which represents its content better.
This patch is a part of my attempts to fix #541.

output: Improve the titles of sections in the development guide

---

README.md

Right now, this is the most common reason for which we reject a patch.
Let's explain contributors what they need to do first, insteads of
telling them in the later review step.

README: Explain how to sign your commit

---

docs/v1.0/out_elasticsearch.txt

Follows up https://github.com/fluent/fluentd-docs/pull/545.
This option is useful to investigate version incompatibility between ES
client and ES server.

elasticsearch: Add validate_client_version description

---

docs/v1.0/in_syslog.txt

To use in_syslog, we normally need to set up our syslog daemon too
(otherwise no one sends data there). I think it's worth adding a
line that explains how to do this.

in_syslog: Explain how to set up the syslog daemon

---

docs/v1.0/faq.txt

This is indeed a "frequently asked" question, popping up several times
on the support forum.
The gotcha is that Alpine Linux has a separate package 'ruby-decimal'
for BigDecimal class, so we need to install the package manually in
order to prevent `require oj` from failing with a LoadError exception.
Related: https://github.com/fluent/fluentd/issues/2136

FAQ: Explain how to use Oj as JSON parser on Alpine Linux

---

docs/v1.0/in_http.txt

I notice developers are actually using Fluentd to collect data from
web pages (using the client side script). So I added an example in
JavaScript.
Also this polishes up the introduction part a bit.

in_http: Add an example program to send data using XMLHTTPRequest

---

docs/v1.0/in_http.txt

This feature is added in Fluentd v1.2.6.
I also added a simple configuration example for the option.

in-http: explain how to use a wildcard in cors_allow_origins

---

docs/v1.0/out_mongo_replset.txt

This option was added in fluent-plugin-mongo v0.8.0 and is now a
required option. Read the project page for details.
> https://github.com/fluent/fluent-plugin-mongo
This patch adds the option to the parameter list and updates the
configuration example.

out_mongo_replset: document the option 'replica_set'

---

docs/v1.0/buffer-plugin-overview.txt
docs/v1.0/buffer-section.txt

This option is new in Fluentd v1.2.6.
https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v126---20181003
I added this option to "Buffer section configuration" and also added a short
mention to the overview page.

buffer: describe "disable_chunk_backup" in the manual pages

---

docs/v1.0/out_rewrite_tag_filter.txt

The one given is incorrect - it just plain doesn't work.  The fixed one works.

tag_parts specification wrong

---

docs/v1.0/out_elasticsearch.txt

This issue is reported in https://github.com/uken/fluent-plugin-elasticsearch/issues/481.
Because time placeholder can work with a chunk which contains timekey
information.
Default buffer configuration does not contain timekey information but
tag information.
Default buffer configuration:
```aconf
<buffer tag>
@type memory
</buffer>
```
When using the above default buffer configuration, elasticseatch plugin does not
extract time placeholder:
index_name fluentd.${tag}.%Y%m%d
-> index_name fluentd.**your.tag**.%Y%m%d
tag and time in chunk_keys:
```aconf
<buffer tag, time>
@type memory
timekey 1h
</buffer>
```
When using buffer configuration with timekey, elasticsearch plugin can
handle time placeholder:
index_name fluentd.${tag}.%Y%m%d
-> index_name fluentd.**your.tag.20181011** …

elasticsearch: Add time chunk_keys supplementary description for time placeholder

---

docs/v1.0/parse-syslog.txt
lib/toc.en.v1.0.rb

This article was previously hosted on `www.fluentd.org`.
https://www.fluentd.org/guides/recipes/parse-syslog
I revised the content of the article so that it became compatible
with Fluentd v1. The example code and log lines in the article were
also updated.

Migrate "Parse Syslog Messages Robustly" from fluentd-website

---

docs/v1.0/api-plugin-filter.txt
docs/v1.0/api-plugin-formatter.txt
docs/v1.0/api-plugin-input.txt
docs/v1.0/api-plugin-output.txt
docs/v1.0/api-plugin-parser.txt
lib/toc.en.v0.14.rb
lib/toc.en.v1.0.rb

There are several links pointing to the (non-existent) article
"/api-plugin-test". This patch fixes up these dead links.

Fix links to the article "Writing Plugin Test Code"

---

docs/v0.12/performance-tuning-multi-process.txt

I fixed a few typographical errors in the document

Fix the typos of Performance Tuning (Multi Process)

---

docs/v1.0/parse-section.txt

Several parser plugins override the default value of the parameter,
which is not mentioned in the current manual page.
This patch adds some documentation about it.

parser: fix the description of the default behaviour of `time_key`

---

docs/v1.0/install-by-chef.txt
lib/toc.en.v1.0.rb

This document is just stmbolic link for previous install-by-chef.txt.
Currently, it is enough for us.
Otherwise, the link for chef recipe is broken:
http://docs.fluentd.org/articles/install-by-chef
This is found in https://www.fluentd.org/faqs.

install-by-chef: Revive install-by-chef document for Fluentd v1

---

docs/v0.10/config-file.txt
docs/v0.12/config-file.txt
docs/v1.0/config-file.txt

An extra space snuck in on the "term"s which made it actually show up on the help webpages.
Commit removes extra space in term.

Remove extra space in config docs

---

docs/v1.0/multi-process-workers.txt

refs: https://github.com/fluent/fluentd/pull/2292

multi-worker-process: Add multiple worker assign syntax description

---

docs/v1.0/config-file.txt
docs/v1.0/in_tcp.txt
docs/v1.0/in_udp.txt
docs/v1.0/out_file.txt

This is a series of patches that reflect recent new features to the documentation.
* Embed ruby expressions into match patterns via `#{...}`
* Embed placeholders into `symlink_path` in `out_file`
* New parameter `source_address_key` for in_udp
* New parameter `source_address_key` for in_tcp
With this, the documentation should catch up with the latest stable release.

Make the documentation v1.4.2 compatible
