app.rb, views/article.erb, views/layout.erb, views/sitemap.erb
We can change $DEFAULT_LANGUAGE to each language for supporting
another language. Translation could be managed by forking repository and setup each language directory.
=> Remove multi language page from official site.

app.rb, lib/toc.en.v0.10.rb, lib/toc.en.v0.12.rb, lib/toc.rb, views/layout.erb
=> Improve multi version

docs/v0.12/formatter-plugin-overview.txt, docs/v0.12/parser-plugin-overview.txt
I wanted to see lists of formatter and parser plugins on overview page
=> list formatter and parser plugins on overview

docs/_formatter_parameters.txt, docs/v0.12/filter-plugin-overview.txt, docs/v0.12/filter_stdout.txt
related: https://github.com/fluent/fluentd/pull/586
=> add docs for filter_stdout

docs/v0.12/filter_record_transformer.txt
for https://github.com/fluent/fluentd/pull/602
=> record_transformer: add docs for renew_time_key

docs/buf_file.txt, docs/faq.txt
@tagomoris Could you check? Need more explanations?
=> Add Limitation section to buf_file

docs/v0.12/config-file.txt
@sonots Do we need more use-cases?
=> Add label section

docs/v0.12/out_forward.txt
=> Add a doc for dns_round_robin option

docs/v0.12/filter-plugin-overview.txt
Fix for this ticket https://github.com/fluent/fluentd-docs/issues/201
=> fix filter plugin example

docs/v0.12/filter-modify-apache.txt, docs/v0.12/forwarding-over-ssl.txt, docs/v0.12/http-to-hdfs.txt, docs/v0.12/logging.txt, docs/v0.12/out_secure_forward.txt, docs/v0.12/out_webhdfs.txt
This is better for reducing config-expander dependency.
=> Use "#{Socket.gethostname}" instead of config-expander's ${hostname}

docs/v0.12/filter_grep.txt, docs/v0.14/filter_grep.txt
Fix https://github.com/fluent/fluentd-docs/issues/238
=> Write about OR condition in filter_grep

docs/v0.12/in_syslog.txt
Ref: https://github.com/fluent/fluentd/issues/1270
=> in_syslog: Add rfc6587 note for TCP protocol

docs/v0.12/in_syslog.txt
I added options to `in_syslog`.
https://github.com/fluent/fluentd/pull/1351
=> Add priority_key/facility_key options to in_syslog

docs/v0.14/plugin-update-from-v12.txt
This is useful for 3rd party plugin authors and users.
=> Add documents about output plugins using mixins

docs/v0.12/life-of-a-fluentd-event.txt
I made my "best guesses" on grammatical changes, hoping to maintain the author's intent/meaning.
=> Grammatical changes to "Life of a Fluentd Event"

docs/v0.12/nodejs.txt
This PR is updated version of current fluentd logger nodejs demo as discussed on #277.
=> Update nodejs demo

docs/v0.14/filter_record_transformer.txt
Except "Need more performance" section because filter_record_modifier
has not been migrated to Fluentd v0.14 API yet.
=> Port updates from docs/v0.12/filter_record_transformer.txt

docs/v0.12/in_forward.txt
I fixed a typo.
mechanizm -> mechanism
=> fix typo mechanizm -> mechanism

docs/v0.14/out_webhdfs.txt
Referenced docs and source code:
- https://docs.fluentd.org/v0.14/articles/buffer-section
- https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin_helper/compat_parameters.rb
- https://github.com/fluent/fluent-plugin-webhdfs/blob/master/lib/fluent/plugin/out_webhdfs.rb
=> Add HDFS (WebHDFS) Output Plugin article for v0.14

docs/v0.12/filter_record_transformer.txt, docs/v0.14/filter_record_transformer.txt
=> record_transformer: Fix keep_keys and remove_keys parameters

docs/v0.14/filter_parser.txt
This change fixes `Fluent::ConfigError` on boot.
=> Use expression instead of format

app.rb, docs/v0.14/api-plugin-helper-record_accessor.txt, docs/v0.14/api-plugin-helper-thread.txt, docs/v0.14/api-plugin-helper-timer.txt, lib/article.rb, lib/toc.en.v0.14.rb
Added basic plugin helper articles.
=> Plugin helper articles

docs/v0.12/java.txt
log function Second parameter must be `map<String, Object>`
=> Fix Java article data object

docs/v0.12/out_rewrite_tag_filter.txt
=> Use rule section instead of deprecated rewriteruleN

docs/v0.14/api-plugin-helper-storage.txt
Sorry for the typo.
It is based on document's word. :cry:
=> Fix a typo

docs/v0.14/plugin-update-from-v12.txt
A lot of plugins have already had requirements section in README.md
=> Add about requirements section

docs/v0.14/api-plugin-formatter.txt
* Use v0.14 style
* Add "Writing tests" for formatter plugins
=> Update "Writing Formatter Plugins"

docs/v0.14/plugin-development.txt
* Add about fluent-plugin-generate
* Add about fluent-plugin-config-format
=> Improve document about plugin-development

docs/v0.14/life-of-a-fluentd-event.txt
minor change - recieved to received
=> fixed a typo

docs/v0.12/life-of-a-fluentd-event.txt
found another typo 
changing received
=> another small cleanup

docs/v0.14/api-plugin-helper-extract.txt, docs/v0.14/api-plugin-helper-formatter.txt, docs/v0.14/api-plugin-helper-inject.txt, docs/v0.14/api-plugin-helper-parser.txt, docs/v0.14/api-plugin-helper-server.txt, docs/v0.14/api-plugin-helper-storage.txt
* extract
* inject
* formatter (format section)
* parser (parse section)
* server (transport section)
* storage
=> Add link from plugin helper to related section

docs/v0.14/plugin-common-parameters.txt
This is useful for users to understand logging.
=> Add link to logging

app.rb, views/layout.erb
=> Fix mixed content

docs/v0.14/performance-tuning.txt, lib/toc.en.v0.14.rb
It is almost same as v0.12's but rewriting multi workers section.
=> Add performance tuning document for v0.14

docs/v0.14/out_s3.txt, lib/toc.en.v0.14.rb
I added `out_s3` document for v0.14 ready version.
=> Add v0.14 version of out_s3 document

docs/v0.12/buffer-plugin-overview.txt
The current documentation introduces novel concepts (like "chunks")
without a proper introduction. So novice readers unfamiliar with the
fluentd internals can be completely lost here.
This patch tries to help them by adding more detailed explanations.
=> docs: Make the flow of overview description to easier to follow.

docs/v1.0/in_syslog.txt
=> Fixed typo

docs/v1.0/monitoring-prometheus.txt
This patch ports a series of fixes applied to the v0.12 article:
- docs: Fix a installation command (1ee685f)
- docs: Fix typos in the "Monitoring by Prometheus" article (99236d5)
- docs: Fix the Prometheus article to support td-agent users (a223575)
For the detail, please see the content of each commit.
=> docs: Update the "Monitoring by Prometheus" article (v1.0)

docs/v0.10/monitoring.txt, docs/v0.12/monitoring-rest-api.txt, docs/v1.0/monitoring-rest-api.txt
I'm not sure what kind of image once existed, but currently it doesn't
exist.
=> Datadog's image does not exist now

docs/v1.0/in_http.txt
I merged the two section 'Tips' and 'Additional Features' into a
single section. Also added a top-level section named 'Enhance
Performance' targeted at the large-scale depolyments (~1k mps).
Also a number of tiny fixes and comments are added. These should
improve the overall readability of the article.
=> in_http: Clean up the structures of sections.

docs/v1.0/td-agent-v2-vs-v3.txt
I've found link labels typos.
---
Windows is always watching you... :sunglasses:
=> td-agent-v2-vs-v3: Correct link labels

docs/v1.0/parser_ltsv.txt
See also https://github.com/fluent/fluentd/pull/1802
=> Add delimiter_pattern document to ltsv_parser

docs/v1.0/plugin-management.txt
We should update this section after release next version of td-agent.
=> Describe Gemfile based plugin management for td-agent3

docs/v1.0/before-install.txt
- Note that td-agent package under systemd already has file descriptor setting handled automatically.
- Minor text adjustments
=> Minor adjustments

docs/v0.10/install-by-deb.txt, docs/v0.10/install-by-rpm.txt, docs/v0.12/install-by-deb.txt, docs/v0.12/install-by-rpm.txt, docs/v1.0/install-by-deb.txt, docs/v1.0/install-by-rpm.txt
It seems to have to exec these commands with "sudo".
(sorry, I don't understand "Signed-off-by" well..... 🙏)
Signed-off-by: Jun Tanaka <tanaka.jun@cloudpayment.co.jp>
=> change to use sudo command with init.d scripts

docs/v1.0/parser_nginx.txt
Signed-off-by: yaron-idan <yaronidan@gmail.com>
=> add http_x_forwarded_for to nginx parsed fields

docs/v1.0/in_http.txt
This is the new feature implemented in Fluentd v1.2.3. The example code
was copied from the original pull request. For details, see:
https://github.com/fluent/fluentd/issues/2047
=> in-http: Explain how to use HTTP compression to reduce payload size

docs/v0.10/changelog.txt, docs/v1.0/changelog.txt
Came across a bad link. Updated to correct change log page for Fluentd.
=> Update link to Fluentd changelog.

docs/v1.0/in_tail.txt
Hi guys, just fixing a small typo in in_tail doc.
=> Fix typo in in_tail doc

docs/v1.0/api-plugin-output.txt
This adds many explanatory notes which I believe make the plugin
template more user-friendly.
Also this patch fixes the title of the article, and cleans up the
introduction part a bit.
For the motivation behind this patch, please read #541.
=> output: Add a bunch of comments to the plugin template

docs/v0.12/out_splunk.txt
=> splunk: Remove outdated mention of Fluentd Enterprise

docs/v1.0/api-plugin-output.txt
This patch is my attempt to improve the overall flow of the explanation.
It also fixes up many, many broken sentences.
=> output: Update the guide on unit testing

docs/v1.0/out_rewrite_tag_filter.txt
Simplified the documentation for the out_rewrite_filter.
=> Documentation improvements for the out_rewrite_filter

docs/v1.0/in_http.txt
I re-read the section and find some explanations a little awkward.
So I fixed these sentences up.
=> in_http: Clean up the "Tips & Tricks" section

docs/v1.0/out_elasticsearch.txt
Due to https://github.com/fluent/fluentd-docs/pull/579#issuecomment-432495305.
=> out_elasticsearch: Replace FAQ with plugin README link

docs/v1.0/multi-process-workers.txt
- I have found typo.
- It is not friendly to the user who copies and pastes from the document, so I made PullRequest.
- If something PullRequest manner is wrong, please contact me.
- test is all green
=> fix system directive typo

app.rb, lib/term.rb, test/test_basic.rb
This is the preparation to upgrade to sinatra2.
=> Suppress warnings

Gemfile, Gemfile.lock, Rakefile, app.rb, app/css/application.css, app/js/application.js, views/layout.erb
Because sinatra-assetpack has been unmaintained since 2015.
I will try upgrading to sinatra2 later.
=> Use sinatra-asset-pipeline instead of sinatra-assetpack

docs/v0.12/parser_json.txt
Signed-off-by: Anselm Eberhardt <aeberhardt@dg-i.net>
=> Add reference to %iso8601 time_format option

docs/v1.0/_time_parameters.txt
See also:
* https://github.com/fluent/fluentd/issues/2183
* https://github.com/fluent/fluentd/issues/679
=> Add note to time_format parameter

docs/v1.0/buffer-section.txt, docs/v1.0/output-plugin-overview.txt
=> Fix typo - exponencial to exponential

docs/v1.0/out_elasticsearch.txt
=> out_elasticsearch: Add logstash_prefix paramter documentation

docs/v1.0/filter_grep.txt, docs/v1.0/in_forward.txt, docs/v1.0/out_forward.txt
Mixing section parameter and top parameter is not good.
Signed-off-by: Masahiro Nakagawa <repeatedly@gmail.com>
=> Add available parameter list to config section

docs/v1.0/filter_geoip.txt
See also https://github.com/y-ken/fluent-plugin-geoip/issues/79
=> filter_geoip: Add geoip_lookup_keys

docs/v1.0/in_unix.txt, lib/toc.en.v1.0.rb
=> Add in_unix document for Fluentd v1

docs/v1.0/output-plugin-overview.txt
Fixes #621 
Signed-off-by: Tsuyoshi Sanda <ts.tsuyoshi.sanda@gmail.com>
=> Fix typo on output-plugin-overview page

docs/v1.0/http-to-td.txt
=> http-to-td: Fix broken links for Treasure Data

docs/v1.0/out_forward.txt
Signed-off-by: bootjp / yoshiaki.ueda <oh@bootjp.me>
Added the parameters added in v1.3.1 to the document.
https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#enhancements-5
https://github.com/fluent/fluentd/pull/2184
=> Add `verify_connection_at_startup` parameter added in v1.3.1

docs/v1.0/out_forward.txt
ref: https://github.com/fluent/fluentd/pull/2393
=> Add keepalive document
